product:
  name: PRODUCT_URL
  appUrl: "http://product-service:8081"

rabbitMq:
  name: RABBITMQ
  image: 
    repository: rabbitmq:3-management
  containerPort: 15672, 5672

rabbitMqCookie:
  name: RABBITMQ_ERLANG_COOKIE
  cookie: "SWQOKODSQALRPCLNMEQG"

rabbitMqDefaultUser:
  name: RABBITMQ_DEFAULT_USER
  user: "rabbitmq"

rabbitMqDefaultPass:
  name: RABBITMQ_DEFAULT_PASS
  pass: "rabbitmq"

rabbitMqDefaultVhost:
  name: RABBITMQ_DEFAULT_VHOST
  vhost: "/"

rabbitMqDefaultHost:
  name: RABBITMQ_DEFAULT_HOST
  host: "rabbitmq-service"

reddisHost:
  name: REDIS_HOST
  host: "redis-service:6379"

catalog:
  msName: catalog
  image:
    repository: wesleywillians/intensivo-catalog
  containerPort: 8080

checkout:
  msName: checkout
  image:
    repository: wesleywillians/intensivo-checkout
  containerPort: 8082

orderPayment:
  msName: orderpayment
  image:
    repository: wesleywillians/intensivo-order:v2
  containerPort: 6572
  args: "payment"

orderPayment:
  msName: order
  image:
    repository: wesleywillians/intensivo-order:v2
  containerPort: 6572
  args: "checkout"