product:
  name: product
  apiUrl: "http://product-service:8081"
  msName: product
  image:
    repository: wesleywillians/intensivo-product
  containerPort: 8081

productService:
  name: product-service
  type: NodePort
  port: 8081
  protocol: TCP
  nodePort: 30080
  selector:
    app: product

rabbitMq:
  name: rabbitmq
  image: 
    repository: rabbitmq:3-management
  containerPort1: 15672
  containerPort2: 5672

rabbitMqService:
  name: rabbitmq-service
  type: ClusterIP
  port: 15672
  protocol: TCP

rabbitMqCookie:
  name: rabbitmq-erlang-cookie
  cookie: "SWQOKODSQALRPCLNMEQG"

rabbitMqDefaultUser:
  name: rabbitmq-default-user
  user: "rabbitmq"

rabbitMqDefaultPass:
  name: rabbitmq-default-pass
  pass: "rabbitmq"

rabbitMqDefaultVhost:
  name: rabbitmq-default-vhost
  vhost: "/"

rabbitMqDefaultHost:
  name: rabbitmq-default-host
  host: "rabbitmq-service"

redis:
  name: redis
  image:
    repository: redis
  containerPort: 6379
  replicas: 1

redisService:
  name: redis-service
  type: ClusterIP
  port: 6379

redisHost:
  name: redis-host
  host: "redis-service:6379"

catalog:
  msName: catalog
  image:
    repository: wesleywillians/intensivo-catalog
  containerPort: 8080

catalogService:
  name: catalog-service
  type: LoadBalancer
  port: 8080
  protocol: TCP
  selector:
    app: catalog

checkout:
  msName: checkout
  image:
    repository: wesleywillians/intensivo-checkout
  containerPort: 8082

orderPayment:
  msName: orderpayment
  image:
    repository: wesleywillians/intensivo-order:v2
  containerPort: 6572
  args: "payment"